### PR TITLE
Adding save/restore and iocStats configurable options

### PR DESCRIPTION
**Pull request by oksanagit**
Hello, 
Offering some additions to make motorSmarAct more user friendly. I.e. optional save/restore and iocsStats. We can shrink auto_settings.req and change the names for more generic.

### CODE REVIEW

**Review by MarkRivers — COMMENTED** [review]
I don't think you need that change to Db/Makefile.  That is installing the iocAdminSoft.db in this applications directory.  This is not necessary, it can just be loading in st.cmd from its original location in DEVIOCSTATS.

**Comment by oksanagit** [comment]
This is correct, I reverted the changes. Also, perhaps save/restore lines in st.cmd might need to be commented as well, as optional.

**Comment by kmpeters** [comment]
Also, github actions doesn't yet know about [iocStats](https://github.com/epics-modules/iocStats).  There are two ways to resolve the github actions build problems:

1. Comment out ``DEVIOCSTATS`` from **EXAMPLE_RELEASE.local.**
2. Add ``DEVIOCSTATS`` can be added to **.ci-local/modules.set**

1 is very easy.  2 is likely to also require changes to **.ci-local/github-actions/post-prepare.py** to properly configure the iocStats module.

**Comment by kmpeters** [comment]
I don't know of any way of testing changes to github-actions builds before commiting and pushing them to the branch, which is one of the reasons why it is so painful.

**Comment by kmpeters** [comment]
The motor_positions.req lines should be moved to an auto_positions.req file that is only restored in pass 0 and is saved more frequencly than the settings:

https://github.com/epics-modules/autosave/blob/503f360c3a0c66867c810006cf43a136a95ae439/asApp/iocsh/save_restore.iocsh#L22-L28

**Comment by prjemian** [comment]
> I don't know of any way of testing changes to github-actions builds before commiting and pushing them to the branch, which is one of the reasons why it is so painful.

One alternative is to interrupt the GH actions workflow midstream, using `tmate`.  See this suggestion I keep in the *hklpy* project repo: https://github.com/bluesky/hklpy/blob/main/.github/tmate.yml

**Comment by prjemian** [comment]
Specifically, this part:

```yaml
    - name: set environment name in YAML file
      shell: bash -l {0}
      run: |
        sed -i.bak "s/name: ${PACKAGE}/name: ${ENV_NAME}/g" environment.yml
    - name: tmate session
      uses: mxschmitt/action-tmate@v3
```

**Comment by kmpeters** [comment]
> The motor_positions.req lines should be moved to an auto_positions.req file that is only restored in pass 0 and is saved more frequencly than the settings:
> 
> https://github.com/epics-modules/autosave/blob/503f360c3a0c66867c810006cf43a136a95ae439/asApp/iocsh/save_restore.iocsh#L22-L28

An alternative to doing that is to include these lines and let autosave create the .req files for you:

https://github.com/epics-modules/xxx/blob/2674bc7985c8d703b22f631bc793d555f09dbb55/iocBoot/iocxxx/common.iocsh#L2-L4

**Comment by kmpeters** [comment]
> > I don't know of any way of testing changes to github-actions builds before commiting and pushing them to the branch, which is one of the reasons why it is so painful.
> 
> One alternative is to interrupt the GH actions workflow midstream, using `tmate`. See this suggestion I keep in the _hklpy_ project repo: https://github.com/bluesky/hklpy/blob/main/.github/tmate.yml

@prjemian, can't anyone in the world connect to the tmate session to take over the github-actions build?

**Comment by kmpeters** [comment]
> @prjemian, can't anyone in the world connect to the tmate session to take over the github-actions build?

I found the answer to my question.  Yes they can, but it is possible to restrict access:

https://github.com/marketplace/actions/debugging-with-tmate#use-registered-public-ssh-keys

**Comment by oksanagit** [comment]
Thank you Kevin!

**Pull request merged**
