### PR TITLE
Don't include a local defition of rint for VxWorks

### LINKED ISSUE #5: Making rint static breaks VxWorks builds
Commit e3ec0a9042414144fc555348b7e11b233e3c3c15 breaks builds on VxWorks:
```
../smarActMCSMotorDriver.cpp: In function 'double rint(double)':
../smarActMCSMotorDriver.cpp:41: error: 'double rint(double)' was declared 'extern' and later 'static'
/APSshare/vw/vxWorks-6.9.4/vxworks-6.9.4/target/h/math.h:104: error: previous declaration of 'double rint(double)'
make[5]: *** [smarActMCSMotorDriver.o] Error 1
make[5]: Leaving directory `/net/s100dserv/xorApps/epics/motor-devel/support/motor-git/modules/motorSmarAct/smarActApp/src/O.vxWorks-ppc32'
make[4]: *** [install.vxWorks-ppc32] Error 2
make[4]: Leaving directory `/net/s100dserv/xorApps/epics/motor-devel/support/motor-git/modules/motorSmarAct/smarActApp/src'
make[3]: *** [src.install] Error 2
make[3]: Leaving directory `/net/s100dserv/xorApps/epics/motor-devel/support/motor-git/modules/motorSmarAct/smarActApp'
make[2]: *** [smarActApp.install] Error 2
make[2]: Leaving directory `/net/s100dserv/xorApps/epics/motor-devel/support/motor-git/modules/motorSmarAct'
make[1]: *** [motorSmarAct.install] Error 2
make[1]: Leaving directory `/net/s100dserv/xorApps/epics/motor-devel/support/motor-git/modules'
make: *** [modules.install] Error 2
```

### PR DESCRIPTION
**Pull request by kmpeters**
Fixes #5

### CODE REVIEW

**Comment by MarkRivers** [comment]
Do you want me to make that change to both files, test on Linux, Windows and vxWorks, and push if successful?

**Comment by kmpeters** [comment]
That would be great.  You should be able to push to the issue5 branch.

**Comment by MarkRivers** [comment]
I have pushed new changed.  The SCU driver does not actually use rint() so I removed the conditional code.  The MCS driver was missing an #endif in your version.

I have tested building on linux-x86, linux-x86_64, vxWorks-ppc32, windows-x64, and windows-x64-static with Visual Studio 2015.

**Comment by kmpeters** [comment]
Thanks!

**Pull request merged**
